language: cpp
env:
  - CXX=g++
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.9 cmake
  - export CXX="g++-4.9" CC="gcc-4.9"
  - $CXX -v
before_script:
  cmake --config=Debug .
script:
  cmake --build . && ctest -V
branches:
  only:
    - master
